/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'karlamaria' at '29/06/16 12:05' with Gradle 2.14
 *
 * @author karlamaria, @date 29/06/16 12:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
